services:
  auth-python:
    build: ./services/auth-python
    ports:
      - "8000:8000"

  billing-csharp:
    build: ./services/billing-csharp
    environment:
      - BILLING_SECRET=topsecretvalue
    expose:
      - "80"


  orders-java:
    build: ./services/orders-java
    ports:
      - "8002:8080"
    links:
      - auth-python
      - billing-csharp
    environment:
      - BILLING_SECRET=topsecretvalue

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
